### ISSUE TITLE
Merge fails if user has the same name across several namespaces

### ISSUE THREAD

**Issue by braykov** [sunny0826/kubecm#1008]
**Describe the bug**
I have a kube config file with 5 namespaces, each has 5 users, but those are all with the same name.
Trying to merge this with another kube config fails.

**To Reproduce**
1. Have 2 namespaces in one cluster
2. Create 2 users in each, but use the same name: cicd-deployer
3. Make sure you have proper kube config file for them
4. Prepare a separate kube config file for another cluster
5. Execute `kubecm merge file1 file2 --config result.yaml

**Expected behavior**
End up with a combined result.yaml kube config file

**Screenshots**

**Desktop (please complete the following information):**
 - MacOS: [e.g. iOS]
 - version 0.31.0

**Additional context**
kubecm assumes different user names and reports an error that this is an invalid kube config file, saying:
`File file1 is not kubeconfig`

Error message like:

error converting *[]NamedAuthInfo into *map[string]*api.AuthInfo: duplicate name "cicd-deployer" in list:...

**Comment by braykov** [comment]
Additionally, I tried putting suffix 1,2,3, etc to the user names to try merging it.
However, I got panic error:

```
Loading KubeConfig file: file1
Add Context: cont1
Add Context: cont2
Add Context: cont3
Add Context: cont4
Add Context: cont5
Loading KubeConfig file:file2
Add Context: cont0
👻 True
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x10537d180]

goroutine 1 [running]:
k8s.io/client-go/tools/clientcmd/api/v1.autoConvert_api_AuthInfo_To_v1_AuthInfo(0x106a6af00?, 0x140005a8ae0?, {0x106d55a60?, 0x1400004e360?})
	k8s.io/client-go@v0.30.0/tools/clientcmd/api/v1/zz_generated.conversion.go:198 +0x20
k8s.io/client-go/tools/clientcmd/api/v1.Convert_api_AuthInfo_To_v1_AuthInfo(...)
	k8s.io/client-go@v0.30.0/tools/clientcmd/api/v1/zz_generated.conversion.go:228
k8s.io/client-go/tools/clientcmd/api/v1.Convert_Map_string_To_Pointer_api_AuthInfo_To_Slice_v1_NamedAuthInfo(0x14000118578, 0x140002349f8, {0x106d55a60, 0x1400004e360})
	k8s.io/client-go@v0.30.0/tools/clientcmd/api/v1/conversion.go:93 +0x20c
k8s.io/client-go/tools/clientcmd/api/v1.autoConvert_api_Config_To_v1_Config(0x14000118540, 0x140002349a0, {0x106d55a60, 0x1400004e360})
	k8s.io/client-go@v0.30.0/tools/clientcmd/api/v1/zz_generated.conversion.go:328 +0x84
k8s.io/client-go/tools/clientcmd/api/v1.Convert_api_Config_To_v1_Config(...)
	k8s.io/client-go@v0.30.0/tools/clientcmd/api/v1/zz_generated.conversion.go:343
k8s.io/client-go/tools/clientcmd/api/v1.RegisterConversions.func8({0x106b73c40?, 0x14000118540?}, {0x106b83300?, 0x140002349a0?}, {0x106d55a60?, 0x1400004e360?})
	k8s.io/client-go@v0.30.0/tools/clientcmd/api/v1/zz_generated.conversion.go:75 +0x64
k8s.io/apimachinery/pkg/conversion.(*Converter).Convert(0x1400066e3c0, {0x106b73c40, 0x14000118540}, {0x106b83300, 0x140002349a0}, 0x1400004e320)
	k8s.io/apimachinery@v0.30.0/pkg/conversion/converter.go:213 +0x2a4
k8s.io/apimachinery/pkg/runtime.(*Scheme).convertToVersion(0x14000625d50, 0x0, {0x106d531d0, 0x14000118540}, {0x106d549d0, 0x140006634a0})
	k8s.io/apimachinery@v0.30.0/pkg/runtime/scheme.go:518 +0x988
k8s.io/apimachinery/pkg/runtime.(*Scheme).UnsafeConvertToVersion(...)
	k8s.io/apimachinery@v0.30.0/pkg/runtime/scheme.go:445
k8s.io/apimachinery/pkg/runtime.unsafeObjectConvertor.ConvertToVersion({0x14000625d50?}, {0x106d531d0?, 0x14000118540?}, {0x106d549d0?, 0x140006634a0?})
	k8s.io/apimachinery@v0.30.0/pkg/runtime/helper.go:39 +0x40
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).doEncode(0x1400061d400, {0x106d531d0, 0x14000118540}, {0x106d4d1d8, 0x140001955c0}, {0x0?, 0x0?})
	k8s.io/apimachinery@v0.30.0/pkg/runtime/serializer/versioning/versioning.go:272 +0x248
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).encode(0x1400061d400, {0x106d531d0?, 0x14000118540}, {0x106d4d1d8, 0x140001955c0}, {0x0, 0x0})
	k8s.io/apimachinery@v0.30.0/pkg/runtime/serializer/versioning/versioning.go:214 +0xfc
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Encode(0x106ada4e0?, {0x106d531d0?, 0x14000118540?}, {0x106d4d1d8?, 0x140001955c0?})
	k8s.io/apimachinery@v0.30.0/pkg/runtime/serializer/versioning/versioning.go:207 +0x34
k8s.io/apimachinery/pkg/runtime.Encode({0x12eda24b8, 0x1400061d400}, {0x106d531d0, 0x14000118540})
	k8s.io/apimachinery@v0.30.0/pkg/runtime/codec.go:49 +0x60
k8s.io/client-go/tools/clientcmd.Write(...)
	k8s.io/client-go@v0.30.0/tools/clientcmd/loader.go:489
k8s.io/client-go/tools/clientcmd.WriteToFile({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x140005a8a80}, 0x140005a8ab0, 0x140005a8ae0, 0x140005a8b10, {0x0, ...}, ...}, ...)
	k8s.io/client-go@v0.30.0/tools/clientcmd/loader.go:442 +0xe4
github.com/sunny0826/kubecm/cmd.WriteConfig(0xa0?, {0x16b0274f4, 0x16}, 0x1400003d080)
	github.com/sunny0826/kubecm/cmd/utils.go:321 +0x9c
github.com/sunny0826/kubecm/cmd.MergeCommand.runMerge({{0x0?}}, 0x63278dda00000000?, {0x1400061f680, 0x2, 0x4})
	github.com/sunny0826/kubecm/cmd/merge.go:93 +0x77c
github.com/sunny0826/kubecm/cmd.(*MergeCommand).Init.func1(0x1400069a300?, {0x1400061f680?, 0x4?, 0x1061c350a?})
	github.com/sunny0826/kubecm/cmd/merge.go:27 +0x3c
github.com/spf13/cobra.(*Command).execute(0x14000697508, {0x1400061f640, 0x4, 0x4})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x14000696008)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
	github.com/sunny0826/kubecm/main.go:30 +0x24
```

**Comment by braykov** [comment]
nevermind
